### ISSUE TITLE
Refactor/rename Preloader

### ISSUE THREAD

**Issue by bgauslin** [bgauslin/moon#1]
Make custom element more flexible, rename it to `ImagePreloader` and try wrapping it around the target element.

HTML:

```html
<image-preloader>
  <figure>
    <img>
  </figure>
</image-preloader>
```

JS:

```js
const imgEl = this.querySelector('img');
// do stuff...
imgEl.setAttribute('ready', '');
```

CSS:

```css
image-preloader img {
  opacity: 0;
  transition: opacity var(--transition);
  visibility: hidden;
}

image-preloader img[ready] {
  opacity: 1;
  visibility: visible;
}

```
